DROP VIEW IF EXISTS "role_full";
DROP VIEW IF EXISTS "permission_full";

DROP TABLE IF EXISTS  "session" CASCADE;
DROP TABLE IF EXISTS  "user" CASCADE;
DROP TABLE IF EXISTS  "role" CASCADE;
DROP TABLE IF EXISTS  "role_info" CASCADE;
DROP TABLE IF EXISTS  "permission" CASCADE;
DROP TABLE IF EXISTS  "permissin_info" CASCADE;
DROP TABLE IF EXISTS  "user_role" CASCADE;
DROP TABLE IF EXISTS  "image" CASCADE;
DROP TABLE IF EXISTS  "locale" CASCADE;
